# -*- coding: utf-8 -*-
"""tensorflow_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oDg0XfoN--Yd9RWQHOV3URB0pJ-X172d
"""

from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import  Sequential,load_model
from sklearn.metrics import accuracy_score
import pandas as pd

df = pd.read_csv('Churn.csv')

x=pd.get_dummies(df.drop([ "Churn","Customer ID"],axis=1))
y=df["Churn"].apply(lambda x:1 if x=="yes" else 0)

X_train,X_test,y_train,y_test = train_test_split(x,y , test_size=0.2)

y_train.head()

model = Sequential()
model.add(Dense(units=32 , activation="relu",input_dim=len(X_train.columns)))
model.add(Dense(units=64 , activation="relu"))
model.add(Dense(units=1 , activation="sigmoid" ))

model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])
model.fit(X_train,y_train, epochs=200 , batch_size=32)

y_hat = model.predict(X_test)
y_hat = [0 if val < 0.5 else 1 for val in y_hat]

accuracy_score(y_test,y_hat)